---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[osl-nginx::default]
  - name: vhost
    run_list:
        - recipe[osl-nginx::project_test]
        - recipe[osl-nginx::logrotate]
    attributes:
        osl-nginx:
            hostname: "test"
