AllCops:
  Include:
    - '**/Berksfile'
    - '**/Cheffile'
  Exclude:
    - 'metadata.rb'

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false
