name             'osl-nginx'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
issues_url       'https://github.com/osuosl-cookbooks/osl-nginx/issues'
source_url       'https://github.com/osuosl-cookbooks/osl-nginx'
license          'Apache-2.0'
chef_version     '>= 16.0'
description      'Installs/Configures osl-nginx'
version          '6.8.0'

depends          'certificate'
depends          'logrotate', '~> 3.0.0'
depends          'nginx', '~> 12.2.0'
depends          'osl-firewall'
depends          'osl-nrpe'
depends          'osl-selinux'

supports         'almalinux', '~> 8.0'
supports         'almalinux', '~> 9.0'
