name             'osl-nginx'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
issues_url       'https://github.com/osuosl-cookbooks/osl-nginx/issues'
source_url       'https://github.com/osuosl-cookbooks/osl-nginx'
license          'Apache-2.0'
chef_version     '>= 14.0'
description      'Installs/Configures osl-nginx'
version          '3.3.0'

depends          'certificate'
depends          'firewall'
depends          'logrotate'
depends          'nginx', '~> 10.3.0'
depends          'osl-munin'
depends          'osl-nrpe'

supports         'centos', '~> 6.0'
supports         'centos', '~> 7.0'
supports         'centos', '~> 8.0'
